---
- name: Backup show run (IOS) commands)
  hosts: all
  connection: local
  tasks:
   - name: run enable level commands
     ios_command:
       commands:
         - show run
     register: print_output
   -  debug: var=print_output.stdout_lines
   - name: Go to the folder and execute command
     command: chdir=~/../etc/ansible ls
   - name: save output to a file
     copy: content="{{ print_output.stdout[0] }}" dest="./output/{{ inventory_hostname }}.cfg"
